#163388254 Add CRUD functionality for articles
andela/ah-bird-box pull request #19
Opened 2019-02-12 21:29 UTC by calebrotich10

#### What does this PR do?
Allows a user to perform CRUD actions on articles using their relevant permissions

#### Description of Task to be completed?
- add tests for articles CRUD
- add ability of user to create, read, update and delete articles
- control user permissions on articles

#### How should this be manually tested?
- Make the following requests to _postman_:

| Request         | URL                | Description |
| ------------- | ------------- |------------------|
| `POST`  | `{BASE_URL}/api/articles/ ` |Create a new article|
| `GET`  | `{BASE_URL}/api/articles/`  |Fetch all articles |
| `GET`  | `{BASE_URL}/api/articles/<slug> ` |Fetch a specific article using its slug|
| `PUT`  | `{BASE_URL}/api/articles/<slug> ` |Update details of a specific article|
| `DELETE`  | `{BASE_URL}/api/articles/<slug> ` |Delete an article|

#### What are the relevant pivotal tracker stories?
[#163388254](https://www.pivotaltracker.com/story/show/163388254)

#### Screenshots (if appropriate)
_**Post an article**_
![image](https://user-images.githubusercontent.com/29451552/52668845-b21c3800-2f25-11e9-99ee-6c292e48e53b.png)

_**Get All articles**_
![image](https://user-images.githubusercontent.com/29451552/52668401-7d5bb100-2f24-11e9-918c-82ac83bfbb38.png)

_**Get Specific Article**_
![image](https://user-images.githubusercontent.com/29451552/52668413-864c8280-2f24-11e9-8a77-e35872e3939b.png)

_**Edit Article**_
![image](https://user-images.githubusercontent.com/29451552/52668370-6d43d180-2f24-11e9-91aa-e0ec8a376956.png)

_**Delete Article**_
![image](https://user-images.githubusercontent.com/29451552/52668433-95cbcb80-2f24-11e9-9b37-ceab896a100d.png)

2019-02-13 06:31 UTC, TooColline commented
It works fine as expected @calebrotich10. Maybe just make the dates format user-friendly.

2019-02-13 07:46 UTC, unah254 commented
Nice work! I believe the author's id will be changed to the author's name once my PR is approved

2019-02-13 07:48 UTC, unah254 reviewed
Works well as expected! However, I feel you should use an author's name instead of id on the response. This will be more appropriate than just seeing an id 1

2019-02-13 12:22 UTC, bryan-munene approved these changes
Works as expected. Just rebase to have one commit and we are good to go

2019-02-13 13:58 UTC, sam-karis requested changes

2019-02-13 13:58 UTC, sam-karis commented on authors/apps/articles/models.py
> +    image_url = CloudinaryField(blank=True, null=True)
Ensure you save both the image and the absolute image URL after the image is uploaded to cloudinary.

2019-02-14 11:17 UTC, sam-karis requested changes

2019-02-14 11:17 UTC, sam-karis commented on authors/apps/articles/tests/base_test.py
> +        url = self.create_list_article_url
I don't the reassignment of `self.create_list_article_url` to `url` is necessary just use `self.create_list_article_url` directly.

2019-02-14 11:17 UTC, sam-karis commented on authors/apps/articles/tests/test_articles.py
> +        data = {
I recommend you put the data in the base test to keep your test clean and concise.

2019-02-14 11:17 UTC, sam-karis commented on authors/apps/articles/tests/test_articles.py
> +        data = {"article": {"title": "Updated Title", "body": "Updated body"}}
Same as above

2019-02-14 14:09 UTC, sam-karis approved these changes
LGTM

2019-02-14 14:09 UTC, merged