Ch set up database 163388243
andela/ah-bird-box pull request #2
Opened 2019-01-29 09:51 UTC by bryan-munene

**What does this PR do?**

SetsUp Postgresql Database as the default database for the application

**Description of Task to be completed?**

Download and configure postgresql database to be the default database for the application

**How should this be manually tested?**

Clone the repo and cd into it

. checkout to the branch git checkout Ch-set-up-database-163388243

. pip install -r requirements.txt

Install postgresql database on your PC.

- create database 'authorshaven'

- create user 'birdbox'

- grant all privileges to database 'authorshaven' to user 'birdbox'

- set the user password as a OS enviroment variable on the terminal. `export DBpass="your password" `

- `python3 manage.py makemigrations` then `python3 manage.py migrate` to test the database 

**Any background context you want to provide?**

None

**What are the relevant pivotal tracker stories?**

[#163388238](https://www.pivotaltracker.com/story/show/163388243)

**Screenshots (if appropriate)**

None

2019-01-29 12:07 UTC, sam-karis requested changes
I suggest you only rebase from `develop` branch only to ensure your PR is easy to understand and follow

2019-01-29 12:07 UTC, sam-karis commented on authors/settings.py
> +        'ENGINE': 'django.db.backends.postgresql',
Hi remove the hard-coded parameters, I suggest you pick them from the environment and you can also try to condense the database url to one variable e.g. `postgresql://username@localhost:5432/db_name`

2019-01-29 12:07 UTC, sam-karis commented on requirements.txt
> +asn1crypto==0.24.0
I don't think your task scope required you to edit all these packages.

2019-01-29 14:14 UTC, bryan-munene commented on authors/settings.py
> +        'ENGINE': 'django.db.backends.postgresql',
Thanks for the feedback. I have implemented it as requested. Please review and let me know


> Hi remove the hard-coded parameters, I suggest you pick them from the environment and you can also try to condense the database url to one variable e.g. `postgresql://username@localhost:5432/db_name`

2019-01-29 15:10 UTC, sam-karis requested changes
Hi good work ensure you add the necessary packages e.g(psycopg2, python-decouple,  dj-database-url) in the `requirements.txt`

2019-01-29 15:14 UTC, bryan-munene commented
> Hi good work ensure you add the necessary packages e.g(psycopg2, python-decouple, dj-database-url) in the `requirements.txt`

all done.

2019-01-30 08:39 UTC, sam-karis approved these changes
LGTM

2019-01-30 08:41 UTC, merged