#163388256 Users should be able to comment on articles
andela/ah-bird-box pull request #21
Opened 2019-02-14 12:41 UTC by TooColline

#### What does this PR do?
This PR Allows users to comment on articles and reply to comments
#### Description of Task to be completed?
- Allow users to comment on articles
- Allow users to reply to comments and replies
- Allow users to get all comments and replies
- Allow users to get specific comments or replies
- Allow users to edit their own comments or replies
- Allow users to delete their own comments or replies
#### How should this be manually tested?
Run the server using ```python manage.py runserver```
Go to Postman:
1. (Ensure there is at least one article posted) Post a comment by sending a ```POST``` request to the URL ```http://127.0.0.1:8000/api/articles/<article-slug>/comments/```
With the data body:
```
{
	"comment" : {
		"body": "This is the second comment"
	}
}
```
2. Post a reply to the existing comment by sending a ```POST``` request to the URL ```http://127.0.0.1:8000/api/articles/<article-slug>/comments/<comment_id>/```
With the data body:
```
{
	"comment" : {
		"body": "This is a reply comment"
	}
}
```
3. Retrieve all the comments from a specific article by sending a ```GET``` request to the URL ```http://127.0.0.1:8000/api/articles/<article-slug>/comments/```
4. Retrieve a specific comment or reply by sending a ```GET``` request to the URL ```http://127.0.0.1:8000/api/articles/t<article-slug>/comments/<comment_id>```
5. Update a comment by sending a ```PUT``` request to ```http://127.0.0.1:8000/api/articles/<article-slug>/comments/<comment_id>/```
With the data body:
```
{
	"comment" : {
		"body": "This is the second updated comment"
	}
}
```
6. Delete a comment/reply by sending a ```DELETE``` request to ```http://127.0.0.1:8000/api/articles/<article-slug>/comments/<comment_id>/```
#### Any background context you want to provide?
Comments will allow authors to get and give feedback on the articles
#### What are the relevant pivotal tracker stories?
[#163388256](https://www.pivotaltracker.com/n/projects/2240063)
#### Screenshots (if appropriate)
**Post Comment**
![image](https://user-images.githubusercontent.com/38856515/52787034-b5224000-306d-11e9-97ef-ef1453c69e3e.png)
**Post a reply**
![image](https://user-images.githubusercontent.com/38856515/52787091-d8e58600-306d-11e9-84ad-f6c1c3f8ced6.png)
**Get all comments**
![image](https://user-images.githubusercontent.com/38856515/52787152-03cfda00-306e-11e9-8765-181a1f12515c.png)
**Get specific comment**
![image](https://user-images.githubusercontent.com/38856515/52787215-34b00f00-306e-11e9-9f97-5b169f5e5ed3.png)
**Update comment**
![image](https://user-images.githubusercontent.com/38856515/52787365-a8521c00-306e-11e9-9bae-09784dc6c1df.png)
**Delete comment**
![image](https://user-images.githubusercontent.com/38856515/52787428-db94ab00-306e-11e9-855b-037509e996e5.png)

#### Questions:

2019-02-14 20:41 UTC, sam-karis requested changes
Good work @TooColline, implement the few changes above and the work will be ready for merging

2019-02-14 20:41 UTC, sam-karis commented on authors/apps/comments/views.py
> +    def get(self, request, id, *args, **kwargs):
I suggest you do away with the `*args` argument is not used anywhere thus not necessary.

2019-02-14 20:41 UTC, sam-karis commented on authors/apps/comments/views.py
> +    def destroy(self, request, id, *args, **kwargs):
The same as above`*args` is not necessary.

2019-02-14 20:41 UTC, sam-karis commented on authors/apps/comments/views.py
> +    def update(self, request, id, *args, **kwargs):
The same as above`*args` is not necessary.

2019-02-14 20:53 UTC, sam-karis approved these changes
LGTM

2019-02-14 20:56 UTC, calebrotich approved these changes
Awesome work @TooColline , works as expected...

2019-02-15 07:15 UTC, bryan-munene approved these changes
Looks Good

2019-02-15 08:02 UTC, merged