#163388271 Track comment edit history
andela/ah-bird-box pull request #27
Opened 2019-02-19 11:21 UTC by TooColline

#### What does this PR do?
This PR merges track comment history to develop branch.
#### Description of Task to be completed?
Allow authenticated users to track the edit history of their comments.
#### How should this be manually tested?
1. Checkout to the branch ```ft-track-comment-history-163388271```
2. Run the server using ```python manage.py runserver```
3. Go to postman and make the following request:

Method | Endpoint | Functionality
--- | --- | ---
GET | `{{base-url}}/articles/<article-slug>/comments/history/` | Retrieve comment history
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#163388271](https://www.pivotaltracker.com/n/projects/2240063)
#### Screenshots (if appropriate)

**Retrieve edit history of a comment that has updates**
![image](https://user-images.githubusercontent.com/38856515/53001809-8f65b400-343c-11e9-842a-02525f148dfd.png)

**Retrieve edit history of a comment that has no updates**
![image](https://user-images.githubusercontent.com/38856515/53011484-86331200-3451-11e9-8f04-df39cb541b1c.png)

**Retrieve edit history of a non-existing article**
![image](https://user-images.githubusercontent.com/38856515/53006827-115ada80-3447-11e9-8883-d52be555ba62.png)

**Retrieve edit history of a non-existing comment**
![image](https://user-images.githubusercontent.com/38856515/53006767-eb353a80-3446-11e9-8f64-c5993e4e52d4.png)

**Retrieve edit history of a comment when unauthorized**
![image](https://user-images.githubusercontent.com/38856515/53006662-b1643400-3446-11e9-944b-0f6d7b44c3cd.png)

#### Questions:
None

2019-02-19 13:58 UTC, sam-karis requested changes
Also, ensure your PR description clearly describe what the PR achieve in `What does this PR do?` section.

2019-02-19 13:58 UTC, sam-karis commented on authors/apps/comments/tests/test_comment_edit_history.py
> +        self.create_comment(
I don't think creating a comment is necessary for this test

2019-02-19 13:58 UTC, sam-karis commented on authors/apps/comments/tests/test_comment_edit_history.py
> +        self.create_article(self.sample_article)
I think creating article and comment is not necessary for this test

2019-02-19 13:58 UTC, sam-karis commented on authors/apps/comments/tests/test_comment_edit_history.py
> +        response = self.client.put(
I think it's not necessary to assign this to a variable since you are not using the response

2019-02-19 13:58 UTC, sam-karis commented on authors/apps/comments/views.py
> +from .serializers import CommentsSerializers, CommentsHistorySerializers
Ensure local imports come below other imports

2019-02-19 13:58 UTC, sam-karis commented on authors/apps/profiles/migrations/0001_initial.py
> +# Generated by Django 2.1.5 on 2019-02-18 15:15
This migration is not necessary for this task

2019-02-19 18:59 UTC, sam-karis approved these changes
LGTM

2019-02-20 06:51 UTC, bryan-munene approved these changes
LGTM

2019-02-20 06:52 UTC, calebrotich approved these changes

2019-02-20 06:59 UTC, unah254 approved these changes
Neat! LGTM

2019-02-20 07:49 UTC, merged