#163388258 Users can follow and unfollow profiles
andela/ah-bird-box pull request #29
Opened 2019-02-19 18:46 UTC by calebrotich10

#### What does this PR do?
This PR enables users to follow, unfollow and view their followers and following lists

#### Description of Task to be completed?
- Create tests
- Implement the `follow` logic
- Implement the `unfollow` logic
- List a user's followers

#### How should this be manually tested?
Make the following requests to postman:
*N/B:* {{BASE_URL}} = `http://127.0.0.1:8000` for localhost and `https://ah-bird-box-staging.herokuapp.com` for heroku

| Request         | URL                | Description |
| ------------- | ------------- |------------------|
| `POST`  | `{{BASE_URL}}/api/profile/<username>/follow/ ` |Follow a user with the specified username|
| `DELETE`  | `{{BASE_URL}}/profile/<username>/follow/`  |Unfollow a user with the specified username |
| `GET`  | `{{BASE_URL}}/api/profile/<username>/following/ ` |List followers and the following list of the user specified by the username|

#### What are the relevant pivotal tracker stories?
[#163388258](https://www.pivotaltracker.com/story/show/163388258)

#### Screenshots (if appropriate)
_*Follow a user*_
![image](https://user-images.githubusercontent.com/29451552/53038940-f0b67300-348e-11e9-9b59-b9903e1352c0.png)

_*Follow a user you already follow*_
![image](https://user-images.githubusercontent.com/29451552/53038913-e8f6ce80-348e-11e9-9986-168e57db9580.png)

_*Unfollow a user*_
![image](https://user-images.githubusercontent.com/29451552/53038952-ff9d2580-348e-11e9-8b9a-91813d6b800a.png)

_*Unfollow a user you do not follow*_
![image](https://user-images.githubusercontent.com/29451552/53038736-83a2dd80-348e-11e9-893b-b7ffecfc769d.png)

_*List followers and unfollowers*_
![image](https://user-images.githubusercontent.com/29451552/53038961-05930680-348f-11e9-9664-1d72328622c7.png)

2019-02-19 19:19 UTC, sam-karis requested changes
Also, ensure you do not have unnecessary migration files e.g this two`authors/apps/profiles/migrations/0003_remove_profile_following.py` and `authors/apps/profiles/migrations/0002_profile_following.py` to one migration file

2019-02-19 19:19 UTC, sam-karis commented on authors/apps/profiles/views.py
> +            "user": serializer.data
Make this message descriptive e.g. `You are now following John Doe`

2019-02-19 19:19 UTC, sam-karis commented on authors/apps/profiles/views.py
> +            "message": "Profile successfully unfollowed",
As above make the response message descriptive e.g.`You stopped following John Doe`

2019-02-20 08:22 UTC, TooColline reviewed
LGTM

2019-02-20 08:27 UTC, bryan-munene approved these changes
This good work. Ensure it works on Heroku

2019-02-20 09:13 UTC, sam-karis approved these changes
LGTM

2019-02-20 09:13 UTC, merged